site_name: GitHub Knowledge Base
site_description: A knowledge base with automatic GitHub versioning
site_author: James Knott
repo_url: https://github.com/armyknife-docs/gh-knowledge-base
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - meta

plugins:
  - search:
      lang: en
      prebuild_index: true
      separator: '[\s\-\.]+'
  - git-revision-date-localized:
      type: date
  - social:
      cards_color:
        fill: "#7e56c2"
        text: "#FFFFFF"
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
  - mkdocs-simple-hooks:
      hooks:
        on_page_markdown: "hooks:on_page_markdown"

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide:
    - Overview: user-guide/index.md
    - Creating Content: user-guide/creating-content.md
  - Contributing: contributing.md
