name: Deploy Documentation

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      {% if cookiecutter.include_git_revision_date == "yes" %}
      - name: Set up Git for versioning
        run: |
          git fetch origin gh-pages --depth=1
      {% endif %}

      - name: Build and deploy documentation
        run: |
          mkdocs gh-deploy --force
